import { RouteInfo } from "./sidebar.metadata";
export const dashboardModuleRoutes: RouteInfo[] = [


  {
    path: "/dashboard/home",
    title: "Home",
    moduleName: "dashboard",
    iconType: "feather",
    icon: "Home",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/dashboard/pages/users",
    title: "Users",
    moduleName: "USER",
    iconType: "feather",
    icon: "users",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/dashboard/pages/albums",
    title: "Album",
    moduleName: "dash",
    iconType: "feather",
    icon: "layers",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },
  {
    path: "/dashboard/pages/photos",
    title: "Photo",
    moduleName: "dash",
    iconType: "feather",
    icon: "user",
    class: "",
    groupTitle: false,
    badge: "",
    badgeClass: "",
    role: ["All"],
    privilege: ["Dashboard"],
    submenu: [],
  },

];
